--liquibase formatted sql

--changeset dmitriy:1
CREATE TABLE IF NOT EXISTS socks
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    color       TEXT    NOT NULL,

    cotton_part INTEGER NOT NULL,

    quantity    INTEGER NOT NULL
);

