version: '3.3'
services:
  db:
    container_name: my-postgres-container
    image: postgres:14.5
    restart: always
    networks:
      - postgres
    env_file:
      - database.env
    ports:
      - '4867:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/

networks:
  postgres:
    driver: bridge

volumes:
  postgres: